language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
env:
  - REQUESTS=2.19.1
  - REQUESTS=2.20.1
  - REQUESTS=2.21.0
  - REQUESTS=2.22.0
install:
  - pip install -q requests==$REQUESTS
  - pip install -r requirements.txt
  - pip install -e .
script: python -m unittest discover tests/ '*test.py'
